### ISSUE TITLE
디바이스 모니터링 페이지 만들기

### ISSUE THREAD

**Issue by zhy2on** [Wave-Net/wavenet-frontend#62]
1. 헤더, 메인, 푸터 전체적인 레이아웃 잡고
2. 각 부분 스타일 지정하기

**Comment by zhy2on** [comment]
<img width="1437" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/99b9ac18-8df6-48d9-aad4-3c350541e6d4">

**Comment by zhy2on** [comment]
<img width="1440" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/1fa5bd1c-0716-4c92-a484-4af5bc4f405b">

**Comment by zhy2on** [comment]
<img width="1440" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/07e81e7a-e849-416f-ac65-53fcebdb4282">

**Comment by zhy2on** [comment]
<img width="1437" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/ae562aba-5186-48d5-987b-57986f90bb01">

**Comment by zhy2on** [comment]
<img width="1440" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/1da1e065-69cf-4ece-9486-0eac858bcf53">

**Comment by zhy2on** [comment]
<img width="1439" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/bf6bbdb4-92dd-4254-a3d0-847b90524fa1">

일단 테이블 연동 되는 거 확인

**Comment by zhy2on** [comment]
<img width="1440" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/6d15a834-3321-44ed-bf3f-78c1606a3cf3">

primevue 라우터 버튼으로 캡쳐 버튼 구현

**Comment by zhy2on** [comment]
<img width="1440" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/7181fa3a-28db-4457-8c08-26281cb37340">
<img width="1440" alt="image" src="https://github.com/Wave-Net/wavenet-frontend/assets/52701529/02c22740-9950-418c-88e8-ccee09367a9d">

완....

**Comment by ihyeeun** [comment]
완전 예뻐요 ,,,, 👍
